---
- hosts: default
  become: true
  vars:
    kernel_dir: /usr/src/kernel

  tasks:
  - name: Make {{kernel_dir}} Directory
    file: path={{kernel_dir}} state=directory

  - name: Uncomment /etc/gai.conf for IPV4
    lineinfile: dest=/etc/gai.conf regexp='#precedence ::ffff:0:0/96  100' line=' precedence ::ffff:0:0/96  100' state=present

  - name: Install GIT
    apt: name={{item}} state=present update_cache=yes
    with_items:
    - git
    - build-essential 

  - name: Clone LINUX kernel
    git: repo=git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git dest={{kernel_dir}} version=v4.12-rc1
